apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: wacommerce-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:29092"
    - name: consumerGroup
      value: "wacommerce-dapr"
    - name: authRequired
      value: "false"
    - name: initialOffset
      value: "newest"
    - name: maxMessageBytes
      value: "1048576"
