apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: wacommerce-statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis:6379"
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "true"
    - name: keyPrefix
      value: "dapr"
    - name: ttlInSeconds
      value: "86400"
