/**
 * Section 41 (requirements traceability) generator.
 *
 * Source of requirements: the stable ticket IDs (TEN/PLT/PAY/MSG/UC/ORD-n)
 * used by SPEC_W37..W46 at the repo root. For each ID this records where it is
 * declared, then greps the repo for references and splits them into
 * implementation vs test/journey files.
 *
 * HONEST LIMITS: this is REFERENCE-based traceability. A file that mentions an
 * ID is evidence someone wired that requirement to that file — not proof the
 * behavior is correct. "IMPLEMENTED+TESTED" here means "has a code reference
 * and a test/journey reference", nothing stronger. IDs with no references are
 * UNKNOWN, not "not implemented" (code may exist without citing the ID).
 */
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "../..");
const specFiles = readdirSync(ROOT).filter((f) => /^SPEC_W(3[7-9]|4\d)\.md$/.test(f)).sort();
const ID_RE = /\b(TEN|PLT|PAY|MSG|UC|ORD)-(\d{1,2})\b/g;

type Req = { id: string; wave: string; line: string };
const reqs = new Map<string, Req>();
for (const f of specFiles) {
  const wave = f.replace("SPEC_", "").replace(".md", "");
  for (const raw of readFileSync(join(ROOT, f), "utf8").split("\n")) {
    for (const m of raw.matchAll(ID_RE)) {
      const id = `${m[1]}-${m[2]}`;
      // prefer a line that *defines* the ticket (id near the start) over a passing mention
      const defines = raw.trimStart().replace(/^[-*#>\d.\s]*\**/, "").startsWith(id);
      const prev = reqs.get(id);
      if (!prev || (defines && !/^\s*[-*#>\d.\s]*\**\s*/.test("") && false) || (defines && prev.line.length === 0)) {
        reqs.set(id, { id, wave, line: raw.trim().replace(/\s+/g, " ").slice(0, 170) });
      } else if (!prev) {
        reqs.set(id, { id, wave, line: raw.trim().replace(/\s+/g, " ").slice(0, 170) });
      }
    }
  }
}

const isTest = (p: string) =>
  /(\.test\.|\.spec\.|_test\.go$)/.test(p) || p.startsWith("simulation/journeys/") || p.startsWith("tests/");
const skip = (p: string) =>
  /^(SPEC_W|node_modules|dist|\.qa\/|IMPLEMENTATION_STATUS|docs\/|simulation\/transcripts|pnpm-lock|package-lock|todo\.md)/.test(p);

function refs(id: string): string[] {
  try {
    const out = execFileSync("git", ["grep", "-l", "-w", "-E", id.replace("-", "[-]")], { cwd: ROOT, encoding: "utf8" });
    return out.split("\n").filter(Boolean).filter((p) => !skip(p));
  } catch {
    return []; // git grep exits 1 on no match
  }
}

const rows = [...reqs.values()].sort((a, b) => {
  const [ka, na] = a.id.split("-"); const [kb, nb] = b.id.split("-");
  return ka === kb ? Number(na) - Number(nb) : ka.localeCompare(kb);
});

let md = `# Requirements traceability (section 41)\n\n`;
md += `Generated by \`.qa/scripts/buildTraceability.ts\` from ${specFiles.length} SPEC files (${specFiles.join(", ")}).\n\n`;
md += `**Method and limits:** reference-based. IMPLEMENTED+TESTED = the ID is cited by at least one non-test source file AND at least one test/journey/e2e file. It shows the requirement was wired to code and to a test — it does **not** prove the behavior is correct. UNKNOWN = the ID is cited nowhere outside the SPEC docs (code may still exist without citing it). Pre-W37 waves (W27–W36) use free-form numbering with no stable IDs and are not covered here.\n\n`;

const tally: Record<string, number> = { "IMPLEMENTED+TESTED": 0, "IMPLEMENTED (no test ref)": 0, "TEST ONLY": 0, UNKNOWN: 0 };
const body: string[] = [];
for (const r of rows) {
  const files = refs(r.id);
  const impl = files.filter((p) => !isTest(p));
  const tests = files.filter(isTest);
  const status = impl.length && tests.length ? "IMPLEMENTED+TESTED"
    : impl.length ? "IMPLEMENTED (no test ref)"
    : tests.length ? "TEST ONLY" : "UNKNOWN";
  tally[status]++;
  const fmt = (xs: string[]) => xs.length ? xs.slice(0, 3).map((x) => `\`${x}\``).join("<br>") + (xs.length > 3 ? `<br>+${xs.length - 3} more` : "") : "—";
  body.push(`| ${r.id} | ${r.wave} | ${r.line.replace(/\|/g, "\\|")} | ${fmt(impl)} | ${fmt(tests)} | ${status} |`);
}
md += `## Summary (${rows.length} distinct ticket IDs)\n\n| Status | Count |\n|---|---:|\n`;
for (const [k, v] of Object.entries(tally)) md += `| ${k} | ${v} |\n`;
md += `\n## Matrix\n\n| ID | Wave | Declared as | Implementation refs | Test / journey refs | Status |\n|---|---|---|---|---|---|\n${body.join("\n")}\n`;
writeFileSync(join(ROOT, ".qa/requirements-matrix.md"), md);
console.log(`wrote .qa/requirements-matrix.md: ${rows.length} IDs`, tally);
