apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: hermes-bridge
    app.kubernetes.io/name: hermes-bridge
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: hermes-bridge-0.1.0
  name: hermes-bridge
  namespace: whatsapp-commerce
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: hermes-bridge
      app.kubernetes.io/name: hermes-bridge
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hermes-bridge
        app.kubernetes.io/name: hermes-bridge
        app.kubernetes.io/version: 0.0.1
        helm.sh/chart: hermes-bridge-0.1.0
    spec:
      containers:
      - env:
        - name: KAFKA_BROKERS
          value: mojaloop-kafka-cluster-kafka-bootstrap.kafka.svc:9092
        - name: OTEL_ENABLED
          value: "true"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.otel.svc.cluster.local:4318
        image: registry.digitalocean.com/talentgraph-auth/whatsapp-hermes-bridge:20260916-1122 # {"$imagepolicy": "flux-system:whatsapp-hermes-bridge"}
        imagePullPolicy: IfNotPresent
        name: hermes-bridge
        ports:
        - containerPort: 8095
          name: port-8095
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 256Mi
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
